import { RawCategoryData } from '../types';

export const DEFAULT_LANGUAGE = 'en';

export const KEYWORDS_BY_CATEGORY: RawCategoryData = {
  identity: [
    'brunette',
    'youth',
    'adolescent',
    'blond',
    'headshot',
    'lady',
    'guy',
    'bald',
    'elder',
    'unshaven',
    'beard',
    'preschool',
    'freckle',
    'chubby',
    'birthday',
    'baby boomer',
    'human',
    'hairdo',
    'sibling',
  ],

  sexual_orientations: [
    'sexy',
    'affection',
    'kiss',
    'embrace',
    'lips',
    'groom',
    'bride',
    'bridal',
    'naker',
    'hip',
    'companion',
    'intimacy',
    'bedroom',
  ],

  political_opinions: [
    'ballot',
    'conference room',
    'Kremlin',
    'formal',
    'cooperation',
    'parliament',
    'politician',
    'corruptness',
    'mayor',
    'air force',
    'navy',
    'referendum',
    'military uniform',
    'authority',
    'presidential',
    'fundraiser',
    'queen',
  ],

  wealth: ['royalty', 'award'],

  social_status_and_activities: [
    'toddler',
    'infancy',
    'adolescence',
    'newborn',
    'offspring',
    'togetherness',
    'nightclub',
    'dancing',
    'club',
    'fiesta',
    'costume',
    'discotheque',
    'sport fan',
    'daddy',
    'parent',
    'race',
    'competition',
    'volunteer',
    'diner',
    'kindergarden',
    'rocker',
    'disco',
    'gown',
    'princess',
    'crew',
    'squad',
    'guest',
    'veteran',
    'wine',
    'alcohol',
    'champagne',
    'spritz',
    'whisky',
    'vodka',
    'liquor',
    'Scotch',
    'rum',
    'pub',
    'Cognac',
    'bourbon',
    'tequila',
    'cocktail',
    'drug',
    'wine bottle',
    'gin',
    'distillery',
    'bowling alley',
    'elementary school',
    'poker',
  ],

  religions: [
    'Buddha',
    'god',
    'sacred',
    'worship',
    'christmas tree',
    'religious belief',
    'priest',
    'prayer',
    'Passover',
    'pope',
    'ritual',
  ],

  ethnicity: ['Eskimo'],

  health: [
    'tiny',
    'laboratory',
    'doctor',
    'patient',
    'medical practitioner',
    'scrutiny',
    'radiography',
    'nurse',
    'research',
    'eyeglasses',
    'dentition',
    'optics',
    'poison',
  ],

  job: [
    'promotion',
    'scientist',
    'classroom',
    'workstation',
    'actress',
    'danser',
    'songwriter',
    'journalist',
    'photojournalist',
    'paparazzi',
    'photojournalism',
    'professional',
    'slide',
    'crash helmet',
    'athlete',
    'presentation',
    'graduation',
    'unemployment',
    'driver',
    'responsibility',
    'recruit',
    'participate',
    'homework',
  ],

  emotions: [
    'innocence',
    'happiness',
    'joy',
    'cheeky',
    'sadness',
    'concentration',
    'enjoyement',
    'freedom',
    'enchantment',
    'facial expression',
    'laughing',
    'worried',
    'pain',
    'despair',
    'serious',
    'confidence',
    'pensive',
    'contemplation',
    'messy',
    'mischief',
    'cry',
    'surprise',
    'rave',
    'loud',
    'shutter',
    'chilled',
    'action energy',
    'exhilaration',
    'confront',
    'generous',
    'prosperity',
    'attractive',
    'look',
    'individuality',
    'angry',
    'loneliness',
    'dandy',
    'solidarity',
    'rebel',
    'humor',
    'loyalty',
    'loyal',
    'merry',
    'obedience',
    'pride',
    'spirit',
    'admiration',
    'enthusiasm',
    'carefree',
    'gorgeous',
  ],
};
