name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      # Install dependencies, cache them correctly
      # and run all Cypress tests
      - name: cypress run
        uses: cypress-io/github-action@v4.2.0
        with:
          install-command: yarn --frozen-lockfile --silent
          build: yarn build
          start: yarn start:ci

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
